name: checks
on:
  pull_request:
env:
  GO_VERSION: 1.15
jobs:
  checks:
    name: checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set up go ${{env.GO_VERSION}}
        uses: actions/setup-go@v2
        with:
          go-version: ${{env.GO_VERSION}}
      - name: Fetch dependencies
        run: |
          make mod
      - name: run tests
        if: always()
        run: make test
